### ISSUE TITLE
Path.home

### ISSUE THREAD

**Issue by FlorianCcj** [Woile/commitizen#2]
hi woile

In commitizen/cli.py
L.82 Path.home() were introduce in python 3.5, i am on python 3.4 how tout patch it ?

Moment I patch it changing l18 3 -> 3.5 ans installing pathlib2 but don t inox if it is the good way

But thanks a lot for this commitizen vert easy tout custom compare to the JS one ^^

**Comment by Woile** [comment]
Hey, glad you like it. I'm working now on the changelog generator, I'll release it in the coming months.

For you problem, if you check at the beginning of the project, versions are being compared. I though every py3 version included `pathlib`, but I guess I was wrong. You'd need to update the comparission done at the beginning (line `22`). You'll have to parse the version 3.4 somehow.

Are you planning on submitting a PR? Otherwise I'll fix it in the coming days.

**Comment by FlorianCcj** [comment]
Thanks it was I thought, but will it install the lib automatically ?

Sorry I let you fix it, I'm not confortable with python and PR

Thanks for all

**Comment by Woile** [comment]
Fixed

Run `pip install -U commitizen` to get the latest version
