### ISSUE TITLE
Restrict list of types / scopes

### ISSUE THREAD

**Issue by waghanza** [Woile/commitizen#24]
Hi @Woile,

Thanks you for this awesome project. 

It really let developers (at least me) focusing on code.

However, I have a little suggestion. I see (in https://woile.github.io/commitizen/config/) that we can specify the format to use.

It could be a great feature (at least for `private` **project**) to have an option to specify
+ `type`s allowed
+ `scope`

What do you think ?

PS : It's more to avoid errors (keeping a flexibility) than restricts

**Comment by Woile** [comment]
Hey I'm glad you like it! Thanks for the kind words.

Regarding the `type` and `scope`. If I understand correct you'd like to use format like:

```
v$minor.$major.$path-$scope-$type
```

The problem with this approach is that you might have more than one commit between versions, so it doesn't make much sense to specify a tag with information of one of those commits, I think it would be quite confusing. What do you think?

**Comment by waghanza** [comment]
Hi,

I think I wasn't clear enough. In fact I'm talking about commit messages.

As conventional commit specifications explain, there could be a `scope`, an optional one.

In some projects, there could be a list of pre-defined `scope`s (as long as a pre-defined list of `type`s).

What I had suggested is to have them into `.cz` file, as long as we can define **per repo** standard.

I hope to be clearer this time

**Comment by Woile** [comment]
Oh sorry, I completely misunderstood it haha.

Ideally this should be done using a [custom rule](https://woile.github.io/commitizen/customization/)

you could even inherit from `ConventionalCommitsCz`

```python
from commitizen.cz.conventional_commits import ConventionalCommitsCz

class ConventionalCommitsScope(ConventionalCommitsCz):
    def questions(self) -> list:
        questions = super().questions()
        questions[2] = {
                "type": "list",
                "name": "scope",
                "message": "Choose your scope",
                "choices": [
                    {
                        "value": "mysuperscope",
                        "name": "this is a crazy scope"
                    }
                ]
        }
       return questions

discover_this = ConventionalCommitsScope
```

You can read more in the link provided on how to create the `setup.py` file.

I think that would solve your problem in the sort term.

Regarding providing a configuration I will try to come up with something. I don't think those values should be part of the global config, because you can write your own commit rules and `scope` and `type` would stop having meaning in the context of your custom rule (different to conventional commits). 

But maybe, there should be a way to customize your current rule through configuration.

```toml
[tool.commitizen.rule-conf.scope]
type = "list"
name = "scope"
message = "Choose your scope"
choices = [{"value": "mysuperscope","name": "this is a crazy scope"}]
```

It would be nice to brainstorm ideas on how to do it. Specially on how to express that if you are not using the `toml` configuration, but the normal `ConfigParser`.
