### ISSUE TITLE
highlight the current option

### ISSUE THREAD

**Issue by Singein** [Woile/commitizen#37]
Just like this: 
![图片](https://user-images.githubusercontent.com/18239246/62820413-83aaad00-bb96-11e9-83ce-ff6f55bba6e5.png)

**Comment by Woile** [comment]
Will add it, thanks

**Comment by Lee-W** [comment]
It seems we can add a style argument to enhance it.

https://github.com/Woile/commitizen/blob/master/commitizen/commands/commit.py#L39

e.g., 

```python
from prompt_toolkit.styles import Style

custom_style_fancy = Style([
    ('qmark', 'fg:#673ab7 bold'),       # token in front of the question
    ('question', 'bold'),               # question text
    ('answer', 'fg:#f44336 bold'),      # submitted answer text behind the question
    ('pointer', 'fg:#673ab7 bold'),     # pointer used in select and checkbox prompts
    ('highlighted', 'fg:#673ab7 bold'), # pointed-at choice in select and checkbox prompts if use_pointer=False
    ('selected', 'fg:#cc5454'),         # style for a selected item of a checkbox
    ('separator', 'fg:#cc5454'),        # separator in lists
    ('instruction', ''),                # user instructions for select, rawselect, checkbox
    ('text', ''),                       # plain text
    ('disabled', 'fg:#858585 italic')   # disabled choices for select and checkbox prompts
])

...

questionary.prompt(questions, style=custom_style_fancy)

...

```

Maybe we can add a default style in `BaseCommitizen`.

https://github.com/Woile/commitizen/blob/master/commitizen/cz/base.py#L5


However, we cannot enable both prompt and the pointed text with color at this time due to the implementation here.

https://github.com/tmbo/questionary/blob/master/questionary/prompts/common.py#L229

Does this make sense to you?
If so, I would like to help with this issue, or maybe we can discuss more on it 🙂

**Comment by Singein** [comment]
Adding a style argument is a good idea!
Thxs~

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Lee-W** [comment]
I've also sent a [PR](https://github.com/tmbo/questionary/pull/27) to [questionary](https://github.com/tmbo/questionary).

**Comment by Woile** [comment]
`v1.7.0` has been released :tada: 
Thanks @Lee-W for the help
